//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCSite.ViewResource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ValidationStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ValidationStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MVCSite.Web.Resources.Models.Account.ValidationStrings", typeof(ValidationStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The new password and confirmation password do not match..
        /// </summary>
        public static string ConfirmationPasswordNotMatch {
            get {
                return ResourceManager.GetString("ConfirmationPasswordNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm new password.
        /// </summary>
        public static string ConfirmNewPassword {
            get {
                return ResourceManager.GetString("ConfirmNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, this email is already in use.
        /// </summary>
        public static string EmailAlreadyUsed {
            get {
                return ResourceManager.GetString("EmailAlreadyUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email address is invalid.
        /// </summary>
        public static string InvalidEmailAddress {
            get {
                return ResourceManager.GetString("InvalidEmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The nick name should be between 4 and 15 characters long..
        /// </summary>
        public static string InvalidNickNameFormat {
            get {
                return ResourceManager.GetString("InvalidNickNameFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords should be at least 6 characters long.
        /// </summary>
        public static string InvalidPasswordFormat {
            get {
                return ResourceManager.GetString("InvalidPasswordFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The phone number is invalid.
        /// </summary>
        public static string InvalidPhoneNumber {
            get {
                return ResourceManager.GetString("InvalidPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name should be at least 4 characters long.
        /// </summary>
        public static string InvalidUserNameLength {
            get {
                return ResourceManager.GetString("InvalidUserNameLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum people must be more than 0 and no less than Minimum People.
        /// </summary>
        public static string MaximumTouristNo {
            get {
                return ResourceManager.GetString("MaximumTouristNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum booking hours in advance must be more than 0.
        /// </summary>
        public static string MinHourAdvance {
            get {
                return ResourceManager.GetString("MinHourAdvance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum people must be more than 0 and no more than Maximum People.
        /// </summary>
        public static string MinimumTouristNo {
            get {
                return ResourceManager.GetString("MinimumTouristNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password.
        /// </summary>
        public static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The new password and confirmation password do not match..
        /// </summary>
        public static string NewPasswordsMustMatch {
            get {
                return ResourceManager.GetString("NewPasswordsMustMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old Password.
        /// </summary>
        public static string OldPassword {
            get {
                return ResourceManager.GetString("OldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords should be at least 6 characters long.
        /// </summary>
        public static string PasswordMinLength {
            get {
                return ResourceManager.GetString("PasswordMinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password and confirmation password do not match..
        /// </summary>
        public static string PasswordsMustMatch {
            get {
                return ResourceManager.GetString("PasswordsMustMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} field is required.
        /// </summary>
        public static string Required {
            get {
                return ResourceManager.GetString("Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Singer Name.
        /// </summary>
        public static string SingerName {
            get {
                return ResourceManager.GetString("SingerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Song Name.
        /// </summary>
        public static string SongName {
            get {
                return ResourceManager.GetString("SongName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter at least  {2} characters  and no more than {1} characters.
        /// </summary>
        public static string StringLengthHint {
            get {
                return ResourceManager.GetString("StringLengthHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter at least  1 characters  and no more than {1} characters.
        /// </summary>
        public static string StringLengthHint1 {
            get {
                return ResourceManager.GetString("StringLengthHint1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This field is required.
        /// </summary>
        public static string TourLanguageSelection {
            get {
                return ResourceManager.GetString("TourLanguageSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter no more than 5 Tour Types.
        /// </summary>
        public static string TourTypeSelection {
            get {
                return ResourceManager.GetString("TourTypeSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, this user name is already in use.
        /// </summary>
        public static string UserNameAlreadyUsed {
            get {
                return ResourceManager.GetString("UserNameAlreadyUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number must be between {1} and {2}.
        /// </summary>
        public static string ValidNumber {
            get {
                return ResourceManager.GetString("ValidNumber", resourceCulture);
            }
        }
    }
}
