//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCSite.DAC.Repositories
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using MVCSite.DAC.Entities;
    
    public partial class GuideDataContext : DbContext
    {
        public GuideDataContext()
            : base("name=GuideDataContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<BankInfo> BankInfoes { get; set; }
        public DbSet<TourExclusion> TourExclusions { get; set; }
        public DbSet<TourInclusion> TourInclusions { get; set; }
        public DbSet<TourPicture> TourPictures { get; set; }
        public DbSet<GuiderExcludedDates> GuiderExcludedDates { get; set; }
        public DbSet<TourSchedule> TourSchedules { get; set; }
        public DbSet<Tour> Tours { get; set; }
        public DbSet<UserWish> UserWishes { get; set; }
        public DbSet<UserTourReview> UserTourReviews { get; set; }
        public DbSet<UserTourBooking> UserTourBookings { get; set; }
        public DbSet<TourExtra> TourExtras { get; set; }
        public DbSet<TourPriceBreakdown> TourPriceBreakdowns { get; set; }
        public DbSet<Promo> Promoes { get; set; }
        public DbSet<TourVendorPromo> TourVendorPromoes { get; set; }
    }
}
