//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCSite.DAC.Repositories
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using MVCSite.DAC.Entities;
    
    public partial class StatDataContext : DbContext
    {
        public StatDataContext()
            : base("name=StatDataContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<MailTemp> MailTemp { get; set; }
        public DbSet<OperationLog> OperationLog { get; set; }
        public DbSet<Pagevar> Pagevar { get; set; }
        public DbSet<UserQueryLog> UserQueryLog { get; set; }
        public DbSet<UserQuerySummary> UserQuerySummary { get; set; }
        public DbSet<CianQuestionLog> CianQuestionLog { get; set; }
        public DbSet<SendEmailLog> SendEmailLog { get; set; }
        public DbSet<QueuedEmails> QueuedEmails { get; set; }
        public DbSet<UniqueVisits> UniqueVisits { get; set; }
        public DbSet<Visits> Visits { get; set; }
        public DbSet<EmailAccountToSend> EmailAccountToSends { get; set; }
    }
}
