//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCSite.ViewResource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ViewStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ViewStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MVCSite.Web.Resources.Views.ViewStrings", typeof(ViewStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Us.
        /// </summary>
        public static string AboutUs {
            get {
                return ResourceManager.GetString("AboutUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Virtual Study Lab is  a Canada company, headquartered in Vancouver,BC,Canada.We have many years of Chinese Mandarin language training experiences. We know your pain of learning Chinese and we could offer anything you want to help. Our vision is to build up a Chinese learning community where we can communicate  together,study together and improve together..
        /// </summary>
        public static string AboutUsInfo {
            get {
                return ResourceManager.GetString("AboutUsInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Wellyours.com is a Chinese Company, headerquarted at Beijing,China. &lt;/p&gt;
        ///    &lt;p&gt;Wellyours,all we are doing are making yours well enough!&lt;/p&gt;
        ///    &lt;p&gt;We beleive that every people has his(her) own potential.The only problem is some of them are NOT detected. Just let Wellyours.com find and activate for you!&lt;/p&gt;
        ///   &lt;p&gt; Tap songs to sing is a music game powered by Wellyours.com.You can sing songs like a professional singer with this!&lt;/p&gt;
        ///   &lt;p&gt; It&apos;s also a perfect tool to practise your fingering skills!&lt;/p [rest of string was truncated]&quot;;.
        /// </summary>
        public static string AboutUsInfoWY {
            get {
                return ResourceManager.GetString("AboutUsInfoWY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept.
        /// </summary>
        public static string Accept {
            get {
                return ResourceManager.GetString("Accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OperationFailed! Touch anywhere on the screen to return..
        /// </summary>
        public static string ActionResultFailedHint {
            get {
                return ResourceManager.GetString("ActionResultFailedHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation Succeeded! Touch anywhere on the screen to return..
        /// </summary>
        public static string ActionResultOKHint {
            get {
                return ResourceManager.GetString("ActionResultOKHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Avatar.
        /// </summary>
        public static string ChangeAvatar {
            get {
                return ResourceManager.GetString("ChangeAvatar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        public static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Personal Information.
        /// </summary>
        public static string ChangePersonalInfo {
            get {
                return ResourceManager.GetString("ChangePersonalInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Topic.
        /// </summary>
        public static string ChangeTopic {
            get {
                return ResourceManager.GetString("ChangeTopic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chapters of &lt;&lt;{0}&gt;&gt;(Total {1} Chapters).
        /// </summary>
        public static string ChaptersOfTopic {
            get {
                return ResourceManager.GetString("ChaptersOfTopic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chats.
        /// </summary>
        public static string Chats {
            get {
                return ResourceManager.GetString("Chats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chat with {0}.
        /// </summary>
        public static string ChatTitle {
            get {
                return ResourceManager.GetString("ChatTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chinese.
        /// </summary>
        public static string Chinese {
            get {
                return ResourceManager.GetString("Chinese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose an action.
        /// </summary>
        public static string ChooseAnAction {
            get {
                return ResourceManager.GetString("ChooseAnAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose File.
        /// </summary>
        public static string ChooseFile {
            get {
                return ResourceManager.GetString("ChooseFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classmates.
        /// </summary>
        public static string Classmates {
            get {
                return ResourceManager.GetString("Classmates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}Comments.
        /// </summary>
        public static string CommentsCount {
            get {
                return ResourceManager.GetString("CommentsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Customer Service Representative.
        /// </summary>
        public static string ContactCSR {
            get {
                return ResourceManager.GetString("ContactCSR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string ContactEmail {
            get {
                return ResourceManager.GetString("ContactEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CSR has not replied your question,thanks for your waiting. We will respond ASAP..
        /// </summary>
        public static string CSRNotReplied {
            get {
                return ResourceManager.GetString("CSRNotReplied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Selection.
        /// </summary>
        public static string CurrentSelection {
            get {
                return ResourceManager.GetString("CurrentSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete completely?.
        /// </summary>
        public static string DeleteConfirm {
            get {
                return ResourceManager.GetString("DeleteConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discovery.
        /// </summary>
        public static string Discovery {
            get {
                return ResourceManager.GetString("Discovery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloaded.
        /// </summary>
        public static string DownloadedHint {
            get {
                return ResourceManager.GetString("DownloadedHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry,failed to change information..
        /// </summary>
        public static string FailedToChange {
            get {
                return ResourceManager.GetString("FailedToChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find classmate!.
        /// </summary>
        public static string FindMateToPractise {
            get {
                return ResourceManager.GetString("FindMateToPractise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Follow Her!.
        /// </summary>
        public static string FollowHer {
            get {
                return ResourceManager.GetString("FollowHer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Follow Him!.
        /// </summary>
        public static string FollowHim {
            get {
                return ResourceManager.GetString("FollowHim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot password?.
        /// </summary>
        public static string ForgotPassword {
            get {
                return ResourceManager.GetString("ForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string FriendlyHint {
            get {
                return ResourceManager.GetString("FriendlyHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friends.
        /// </summary>
        public static string Friends {
            get {
                return ResourceManager.GetString("Friends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global Users.
        /// </summary>
        public static string GlobalUsers {
            get {
                return ResourceManager.GetString("GlobalUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Got {0} results.
        /// </summary>
        public static string GotNSearchResults {
            get {
                return ResourceManager.GetString("GotNSearchResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Name.
        /// </summary>
        public static string ImageName {
            get {
                return ResourceManager.GetString("ImageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initial(3 chars or less).
        /// </summary>
        public static string Initial {
            get {
                return ResourceManager.GetString("Initial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please input here.
        /// </summary>
        public static string InputHere {
            get {
                return ResourceManager.GetString("InputHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please input search keywords here.
        /// </summary>
        public static string InputSearchKeyword {
            get {
                return ResourceManager.GetString("InputSearchKeyword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;
        ///             Sorry. A system Error Occured.
        ///            &lt;/p&gt;
        ///          .
        /// </summary>
        public static string InternalError {
            get {
                return ResourceManager.GetString("InternalError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry,internal error happened:(.
        /// </summary>
        public static string InternalErrorHappened {
            get {
                return ResourceManager.GetString("InternalErrorHappened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait to be accepted.
        /// </summary>
        public static string InvitationUnaccepted {
            get {
                return ResourceManager.GetString("InvitationUnaccepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Add This Song For Me!.
        /// </summary>
        public static string IWantThisSong {
            get {
                return ResourceManager.GetString("IWantThisSong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Comment Time.
        /// </summary>
        public static string LastCommentTime {
            get {
                return ResourceManager.GetString("LastCommentTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login with Google account.
        /// </summary>
        public static string LoginWithGoogleAccount {
            get {
                return ResourceManager.GetString("LoginWithGoogleAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login with MSN(Windows Live) account.
        /// </summary>
        public static string LoginWithMSNAccount {
            get {
                return ResourceManager.GetString("LoginWithMSNAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Images.
        /// </summary>
        public static string ManageImages {
            get {
                return ResourceManager.GetString("ManageImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Me!.
        /// </summary>
        public static string Me {
            get {
                return ResourceManager.GetString("Me", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}&apos;s Settings.
        /// </summary>
        public static string MySettings {
            get {
                return ResourceManager.GetString("MySettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password.
        /// </summary>
        public static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password Again.
        /// </summary>
        public static string NewPasswordAgain {
            get {
                return ResourceManager.GetString("NewPasswordAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Page.
        /// </summary>
        public static string NextPage {
            get {
                return ResourceManager.GetString("NextPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nick Name(2 chars or more).
        /// </summary>
        public static string NickName {
            get {
                return ResourceManager.GetString("NickName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have no friends now,please go to Classmates Tab to select one to practise together.
        /// </summary>
        public static string NoFriendYet {
            get {
                return ResourceManager.GetString("NoFriendYet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, You do NOT have rights..
        /// </summary>
        public static string NoRights {
            get {
                return ResourceManager.GetString("NoRights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Found?.
        /// </summary>
        public static string NotFound {
            get {
                return ResourceManager.GetString("NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Sorry. The page is not found.&lt;/p&gt;
        ///          .
        /// </summary>
        public static string NotFoundError {
            get {
                return ResourceManager.GetString("NotFoundError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old Password.
        /// </summary>
        public static string OldPassword {
            get {
                return ResourceManager.GetString("OldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry!your operation failed,please check your input and try later..
        /// </summary>
        public static string OperationFaileCheckTryLater {
            get {
                return ResourceManager.GetString("OperationFaileCheckTryLater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string Options {
            get {
                return ResourceManager.GetString("Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speaking English.
        /// </summary>
        public static string OralEnglish {
            get {
                return ResourceManager.GetString("OralEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Part {0}.
        /// </summary>
        public static string PartOf {
            get {
                return ResourceManager.GetString("PartOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please input your introduction to let others remember you at once.
        /// </summary>
        public static string PlaceHolderSelfIntro {
            get {
                return ResourceManager.GetString("PlaceHolderSelfIntro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please input your study target,e.g. learn daily chinese.
        /// </summary>
        public static string PlaceHolderStudyTarget {
            get {
                return ResourceManager.GetString("PlaceHolderStudyTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play.
        /// </summary>
        public static string Play {
            get {
                return ResourceManager.GetString("Play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play All.
        /// </summary>
        public static string PlayAll {
            get {
                return ResourceManager.GetString("PlayAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select Topic.
        /// </summary>
        public static string PleaseSelectTopic {
            get {
                return ResourceManager.GetString("PleaseSelectTopic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poster.
        /// </summary>
        public static string Poster {
            get {
                return ResourceManager.GetString("Poster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post Time.
        /// </summary>
        public static string PostTime {
            get {
                return ResourceManager.GetString("PostTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Practice With Her!.
        /// </summary>
        public static string PracticeWithHer {
            get {
                return ResourceManager.GetString("PracticeWithHer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Practice With Him!.
        /// </summary>
        public static string PracticeWithHim {
            get {
                return ResourceManager.GetString("PracticeWithHim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Recording.
        /// </summary>
        public static string PressHereToSpeak {
            get {
                return ResourceManager.GetString("PressHereToSpeak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview.
        /// </summary>
        public static string Preview {
            get {
                return ResourceManager.GetString("Preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous Page.
        /// </summary>
        public static string PreviousPage {
            get {
                return ResourceManager.GetString("PreviousPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pull down to refresh....
        /// </summary>
        public static string PullDownToRefresh {
            get {
                return ResourceManager.GetString("PullDownToRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pull up to refresh....
        /// </summary>
        public static string PullUpToRefresh {
            get {
                return ResourceManager.GetString("PullUpToRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to quit?.
        /// </summary>
        public static string QuitConfirm {
            get {
                return ResourceManager.GetString("QuitConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to These {0} users are studying the same subject with you,practise together?.
        /// </summary>
        public static string RecommendedUser4You {
            get {
                return ResourceManager.GetString("RecommendedUser4You", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record Again!.
        /// </summary>
        public static string RecordAgain {
            get {
                return ResourceManager.GetString("RecordAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refuse.
        /// </summary>
        public static string Refuse {
            get {
                return ResourceManager.GetString("Refuse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry,upload image failed! Please reselect an image and upload again..
        /// </summary>
        public static string ReselectUploadImgAgain {
            get {
                return ResourceManager.GetString("ReselectUploadImgAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources.
        /// </summary>
        public static string Resources {
            get {
                return ResourceManager.GetString("Resources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt; Return!.
        /// </summary>
        public static string Return {
            get {
                return ResourceManager.GetString("Return", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save!.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Say Hello!.
        /// </summary>
        public static string SayHello {
            get {
                return ResourceManager.GetString("SayHello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Say Image In Chinese.
        /// </summary>
        public static string SayImage {
            get {
                return ResourceManager.GetString("SayImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Dictionary.
        /// </summary>
        public static string SearchDictionary {
            get {
                return ResourceManager.GetString("SearchDictionary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searching in dictionary finished on local,no traffic at all..
        /// </summary>
        public static string SearchOnLocalNoTraffic {
            get {
                return ResourceManager.GetString("SearchOnLocalNoTraffic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a contact to send.
        /// </summary>
        public static string SelectAContactToSend {
            get {
                return ResourceManager.GetString("SelectAContactToSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select game contents.
        /// </summary>
        public static string SelectGameContents {
            get {
                return ResourceManager.GetString("SelectGameContents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Introduction.
        /// </summary>
        public static string SelfIntroduction {
            get {
                return ResourceManager.GetString("SelfIntroduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send error report!.
        /// </summary>
        public static string SendErrorReport {
            get {
                return ResourceManager.GetString("SendErrorReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Message to CSR.
        /// </summary>
        public static string SendMsgToCSR {
            get {
                return ResourceManager.GetString("SendMsgToCSR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send To Classmate.
        /// </summary>
        public static string SendToClassmate {
            get {
                return ResourceManager.GetString("SendToClassmate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Center.
        /// </summary>
        public static string ServiceCenter {
            get {
                return ResourceManager.GetString("ServiceCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sex.
        /// </summary>
        public static string Sex {
            get {
                return ResourceManager.GetString("Sex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can you tell the exact Chinese word and related sentence patterns in the following picture?.
        /// </summary>
        public static string ShareImgSummary {
            get {
                return ResourceManager.GetString("ShareImgSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Word picture dictionary-{0}.
        /// </summary>
        public static string ShareImgTitle {
            get {
                return ResourceManager.GetString("ShareImgTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slow.
        /// </summary>
        public static string Slow {
            get {
                return ResourceManager.GetString("Slow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speak something with this image.
        /// </summary>
        public static string SpeakWithImage {
            get {
                return ResourceManager.GetString("SpeakWithImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard.
        /// </summary>
        public static string Standard {
            get {
                return ResourceManager.GetString("Standard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop Recording.
        /// </summary>
        public static string StopRecording {
            get {
                return ResourceManager.GetString("StopRecording", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Study Target.
        /// </summary>
        public static string StudyTarget {
            get {
                return ResourceManager.GetString("StudyTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Study Topic - &lt;&lt;{0}&gt;&gt;.
        /// </summary>
        public static string StudyTopic {
            get {
                return ResourceManager.GetString("StudyTopic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You invite too many users to chat!.
        /// </summary>
        public static string TooManyUsersToChat {
            get {
                return ResourceManager.GetString("TooManyUsersToChat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Total {0} Chapters).
        /// </summary>
        public static string TotalChapterNo {
            get {
                return ResourceManager.GetString("TotalChapterNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total {0} Parts.
        /// </summary>
        public static string TotalPartNo {
            get {
                return ResourceManager.GetString("TotalPartNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Total {0} Sentences).
        /// </summary>
        public static string TotalSentenceNo {
            get {
                return ResourceManager.GetString("TotalSentenceNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total {0} songs for downloading(Added everyday).
        /// </summary>
        public static string TotalSongs {
            get {
                return ResourceManager.GetString("TotalSongs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Units.
        /// </summary>
        public static string UnitHint {
            get {
                return ResourceManager.GetString("UnitHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload.
        /// </summary>
        public static string Upload {
            get {
                return ResourceManager.GetString("Upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I want to upload image!.
        /// </summary>
        public static string UploadChatImage {
            get {
                return ResourceManager.GetString("UploadChatImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Information.
        /// </summary>
        public static string UserInformation {
            get {
                return ResourceManager.GetString("UserInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name(4 chars or more).
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to These users want to be your friends.
        /// </summary>
        public static string UsersWantedToBeFriends {
            get {
                return ResourceManager.GetString("UsersWantedToBeFriends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string VJiaoshiIsLoading4You {
            get {
                return ResourceManager.GetString("VJiaoshiIsLoading4You", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You made a voice record!.
        /// </summary>
        public static string YouMadeAVoiceRecord {
            get {
                return ResourceManager.GetString("YouMadeAVoiceRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your song request was submited.Please wait for our editors to finish it for you and check here later.Thanks for your patience!.
        /// </summary>
        public static string YourSongRequestSubmitted {
            get {
                return ResourceManager.GetString("YourSongRequestSubmitted", resourceCulture);
            }
        }
    }
}
