//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCSite.EmailService
{
    using System;
    using System.Collections.Generic;
    
    public partial class SendEmailLog
    {
        public System.Guid ID { get; set; }
        public string Sender { get; set; }
        public string Receiver { get; set; }
        public string Title { get; set; }
        public string Body { get; set; }
        public System.DateTime EnterTime { get; set; }
        public System.DateTime SendTime { get; set; }
        public bool SendResult { get; set; }
        public byte SiteType { get; set; }
        public int EMailType { get; set; }
    }
}
