//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCSite.ViewResource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ViewStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ViewStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MVCSite.Web.Resources.Views.ViewStrings", typeof(ViewStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept.
        /// </summary>
        public static string Accept {
            get {
                return ResourceManager.GetString("Accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OperationFailed! Touch anywhere on the screen to return..
        /// </summary>
        public static string ActionResultFailedHint {
            get {
                return ResourceManager.GetString("ActionResultFailedHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation Succeeded! Touch anywhere on the screen to return..
        /// </summary>
        public static string ActionResultOKHint {
            get {
                return ResourceManager.GetString("ActionResultOKHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Avatar.
        /// </summary>
        public static string ChangeAvatar {
            get {
                return ResourceManager.GetString("ChangeAvatar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        public static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Personal Information.
        /// </summary>
        public static string ChangePersonalInfo {
            get {
                return ResourceManager.GetString("ChangePersonalInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Topic.
        /// </summary>
        public static string ChangeTopic {
            get {
                return ResourceManager.GetString("ChangeTopic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chapters of &lt;&lt;{0}&gt;&gt;.
        /// </summary>
        public static string ChaptersOfTopic {
            get {
                return ResourceManager.GetString("ChaptersOfTopic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chats.
        /// </summary>
        public static string Chats {
            get {
                return ResourceManager.GetString("Chats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chinese.
        /// </summary>
        public static string Chinese {
            get {
                return ResourceManager.GetString("Chinese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose an action.
        /// </summary>
        public static string ChooseAnAction {
            get {
                return ResourceManager.GetString("ChooseAnAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose File.
        /// </summary>
        public static string ChooseFile {
            get {
                return ResourceManager.GetString("ChooseFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classmates.
        /// </summary>
        public static string Classmates {
            get {
                return ResourceManager.GetString("Classmates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Selection.
        /// </summary>
        public static string CurrentSelection {
            get {
                return ResourceManager.GetString("CurrentSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discovery.
        /// </summary>
        public static string Discovery {
            get {
                return ResourceManager.GetString("Discovery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloaded.
        /// </summary>
        public static string DownloadedHint {
            get {
                return ResourceManager.GetString("DownloadedHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find classmate!.
        /// </summary>
        public static string FindMateToPractise {
            get {
                return ResourceManager.GetString("FindMateToPractise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Follow Her!.
        /// </summary>
        public static string FollowHer {
            get {
                return ResourceManager.GetString("FollowHer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Follow Him!.
        /// </summary>
        public static string FollowHim {
            get {
                return ResourceManager.GetString("FollowHim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string FriendlyHint {
            get {
                return ResourceManager.GetString("FriendlyHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friends.
        /// </summary>
        public static string Friends {
            get {
                return ResourceManager.GetString("Friends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global Users.
        /// </summary>
        public static string GlobalUsers {
            get {
                return ResourceManager.GetString("GlobalUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VirtualStudyLab got {0} results for you.
        /// </summary>
        public static string GotNSearchResults {
            get {
                return ResourceManager.GetString("GotNSearchResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please input search keywords here.
        /// </summary>
        public static string InputSearchKeyword {
            get {
                return ResourceManager.GetString("InputSearchKeyword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Me!.
        /// </summary>
        public static string Me {
            get {
                return ResourceManager.GetString("Me", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}&apos;s Settings.
        /// </summary>
        public static string MySettings {
            get {
                return ResourceManager.GetString("MySettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Page.
        /// </summary>
        public static string NextPage {
            get {
                return ResourceManager.GetString("NextPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have no friends now,please go to Classmates Tab to select one to practise together.
        /// </summary>
        public static string NoFriendYet {
            get {
                return ResourceManager.GetString("NoFriendYet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string Options {
            get {
                return ResourceManager.GetString("Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speaking English.
        /// </summary>
        public static string OralEnglish {
            get {
                return ResourceManager.GetString("OralEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Part {0}.
        /// </summary>
        public static string PartOf {
            get {
                return ResourceManager.GetString("PartOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please input your introduction to let others remember you at once.
        /// </summary>
        public static string PlaceHolderSelfIntro {
            get {
                return ResourceManager.GetString("PlaceHolderSelfIntro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please input your study target,e.g. learn daily chinese.
        /// </summary>
        public static string PlaceHolderStudyTarget {
            get {
                return ResourceManager.GetString("PlaceHolderStudyTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play.
        /// </summary>
        public static string Play {
            get {
                return ResourceManager.GetString("Play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play All.
        /// </summary>
        public static string PlayAll {
            get {
                return ResourceManager.GetString("PlayAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select Topic.
        /// </summary>
        public static string PleaseSelectTopic {
            get {
                return ResourceManager.GetString("PleaseSelectTopic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Practice With Her!.
        /// </summary>
        public static string PracticeWithHer {
            get {
                return ResourceManager.GetString("PracticeWithHer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Practice With Him!.
        /// </summary>
        public static string PracticeWithHim {
            get {
                return ResourceManager.GetString("PracticeWithHim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press Here To Speak!.
        /// </summary>
        public static string PressHereToSpeak {
            get {
                return ResourceManager.GetString("PressHereToSpeak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous Page.
        /// </summary>
        public static string PreviousPage {
            get {
                return ResourceManager.GetString("PreviousPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pull down to refresh....
        /// </summary>
        public static string PullDownToRefresh {
            get {
                return ResourceManager.GetString("PullDownToRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pull up to refresh....
        /// </summary>
        public static string PullUpToRefresh {
            get {
                return ResourceManager.GetString("PullUpToRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to These users are studying the same subject with you,practise together?.
        /// </summary>
        public static string RecommendedUser4You {
            get {
                return ResourceManager.GetString("RecommendedUser4You", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record Again!.
        /// </summary>
        public static string RecordAgain {
            get {
                return ResourceManager.GetString("RecordAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refuse.
        /// </summary>
        public static string Refuse {
            get {
                return ResourceManager.GetString("Refuse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources.
        /// </summary>
        public static string Resources {
            get {
                return ResourceManager.GetString("Resources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt; Return!.
        /// </summary>
        public static string Return {
            get {
                return ResourceManager.GetString("Return", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Say Hello!.
        /// </summary>
        public static string SayHello {
            get {
                return ResourceManager.GetString("SayHello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Dictionary.
        /// </summary>
        public static string SearchDictionary {
            get {
                return ResourceManager.GetString("SearchDictionary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searching in dictionary finished on local,no traffic at all..
        /// </summary>
        public static string SearchOnLocalNoTraffic {
            get {
                return ResourceManager.GetString("SearchOnLocalNoTraffic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a contact to send.
        /// </summary>
        public static string SelectAContactToSend {
            get {
                return ResourceManager.GetString("SelectAContactToSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select game contents.
        /// </summary>
        public static string SelectGameContents {
            get {
                return ResourceManager.GetString("SelectGameContents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Self Introduction.
        /// </summary>
        public static string SelfIntroduction {
            get {
                return ResourceManager.GetString("SelfIntroduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send error report!.
        /// </summary>
        public static string SendErrorReport {
            get {
                return ResourceManager.GetString("SendErrorReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send To Classmate.
        /// </summary>
        public static string SendToClassmate {
            get {
                return ResourceManager.GetString("SendToClassmate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slow.
        /// </summary>
        public static string Slow {
            get {
                return ResourceManager.GetString("Slow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard.
        /// </summary>
        public static string Standard {
            get {
                return ResourceManager.GetString("Standard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Study Topic - &lt;&lt;{0}&gt;&gt;.
        /// </summary>
        public static string StudyTopic {
            get {
                return ResourceManager.GetString("StudyTopic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You invite too many users to chat!.
        /// </summary>
        public static string TooManyUsersToChat {
            get {
                return ResourceManager.GetString("TooManyUsersToChat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Total {0} Chapters).
        /// </summary>
        public static string TotalChapterNo {
            get {
                return ResourceManager.GetString("TotalChapterNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total {0} Parts.
        /// </summary>
        public static string TotalPartNo {
            get {
                return ResourceManager.GetString("TotalPartNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Units.
        /// </summary>
        public static string UnitHint {
            get {
                return ResourceManager.GetString("UnitHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload.
        /// </summary>
        public static string Upload {
            get {
                return ResourceManager.GetString("Upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Information.
        /// </summary>
        public static string UserInformation {
            get {
                return ResourceManager.GetString("UserInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to These users want to be your friends.
        /// </summary>
        public static string UsersWantedToBeFriends {
            get {
                return ResourceManager.GetString("UsersWantedToBeFriends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You made a voice record!.
        /// </summary>
        public static string YouMadeAVoiceRecord {
            get {
                return ResourceManager.GetString("YouMadeAVoiceRecord", resourceCulture);
            }
        }
    }
}
