//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCSite.ViewResource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GuideStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GuideStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MVCSite.Web.Resources.Views.Guide.GuideStrings", typeof(GuideStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e.g. Hotel Pickup and Drop-off.
        /// </summary>
        public static string ExclusionPlaceholder1 {
            get {
                return ResourceManager.GetString("ExclusionPlaceholder1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e.g. Gratuities.
        /// </summary>
        public static string ExclusionPlaceholder2 {
            get {
                return ResourceManager.GetString("ExclusionPlaceholder2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ExclusionPlaceholder3 {
            get {
                return ResourceManager.GetString("ExclusionPlaceholder3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e.g. Transport by air-conditioned vechicle.
        /// </summary>
        public static string InclusionPlaceholder1 {
            get {
                return ResourceManager.GetString("InclusionPlaceholder1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e.g. Entrance fee is included.
        /// </summary>
        public static string InclusionPlaceholder2 {
            get {
                return ResourceManager.GetString("InclusionPlaceholder2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e.g. Lunch.
        /// </summary>
        public static string InclusionPlaceholder3 {
            get {
                return ResourceManager.GetString("InclusionPlaceholder3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a retail price that is at least 12% higher than net price.
        /// </summary>
        public static string SugRetailPriceTooSmall {
            get {
                return ResourceManager.GetString("SugRetailPriceTooSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter at least 1 character and no more than 300 characters.
        /// </summary>
        public static string TourExclusionExtraValidationMessage {
            get {
                return ResourceManager.GetString("TourExclusionExtraValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter at least 1 character and no more than 300 characters.
        /// </summary>
        public static string TourInclusionExtraValidationMessage {
            get {
                return ResourceManager.GetString("TourInclusionExtraValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bounds of this rule conflict with the rule above on line #.
        /// </summary>
        public static string TourPriceBreakdownExtraValidationMessage {
            get {
                return ResourceManager.GetString("TourPriceBreakdownExtraValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bounds of this rule conflict with the rule above on line #.
        /// </summary>
        public static string TourPriceBreakdownValidationMessage {
            get {
                return ResourceManager.GetString("TourPriceBreakdownValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bounds of this rule conflict with the rule above on line #.
        /// </summary>
        public static string TourVendorPromoExtraValidationMessage {
            get {
                return ResourceManager.GetString("TourVendorPromoExtraValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bounds of this rule conflict with the rule above on line #.
        /// </summary>
        public static string TourVendorPromoValidationMessage {
            get {
                return ResourceManager.GetString("TourVendorPromoValidationMessage", resourceCulture);
            }
        }
    }
}
