//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace MVCSite.DAC.Entities
{
    public partial class Category
    {
        #region Primitive Properties
    
        public virtual int ID
        {
            get;
            set;
        }
    
        public virtual string Name
        {
            get;
            set;
        }
    
        public virtual System.DateTime EnterTime
        {
            get;
            set;
        }
    
        public virtual System.DateTime ModifyTime
        {
            get;
            set;
        }
    
        public virtual string Intro
        {
            get;
            set;
        }
    
        public virtual string DestinationList
        {
            get;
            set;
        }
    
        public virtual string BlogList
        {
            get;
            set;
        }
    
        public virtual string Tip1
        {
            get;
            set;
        }
    
        public virtual string Tip2
        {
            get;
            set;
        }
    
        public virtual string Tip3
        {
            get;
            set;
        }
    
        public virtual string Tip4
        {
            get;
            set;
        }
    
        public virtual string Tip5
        {
            get;
            set;
        }
    
        public virtual string Tip6
        {
            get;
            set;
        }

        #endregion

    }
}
