//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace MVCSite.DAC.Entities
{
    public partial class CianQuestionLog
    {
        #region Primitive Properties
    
        public virtual System.Guid ID
        {
            get;
            set;
        }
    
        public virtual string Question
        {
            get;
            set;
        }
    
        public virtual string AnswerResult
        {
            get;
            set;
        }
    
        public virtual System.DateTime EnterTime
        {
            get;
            set;
        }
    
        public virtual int CategoryID
        {
            get;
            set;
        }
    
        public virtual int DirectionID
        {
            get;
            set;
        }
    
        public virtual string DirectionString
        {
            get;
            set;
        }
    
        public virtual string CategoryString
        {
            get;
            set;
        }
    
        public virtual Nullable<int> UserID
        {
            get;
            set;
        }

        #endregion

    }
}
