//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace MVCSite.DAC.Entities
{
    public partial class Country
    {
        #region Primitive Properties
    
        public virtual int country_id
        {
            get;
            set;
        }
    
        public virtual string description
        {
            get;
            set;
        }
    
        public virtual bool isbanned
        {
            get;
            set;
        }
    
        public virtual string abbreviation
        {
            get;
            set;
        }
    
        public virtual string Intro
        {
            get;
            set;
        }
    
        public virtual string DestinationList
        {
            get;
            set;
        }
    
        public virtual string BlogList
        {
            get;
            set;
        }
    
        public virtual string Tip1
        {
            get;
            set;
        }
    
        public virtual string Tip2
        {
            get;
            set;
        }
    
        public virtual string Tip3
        {
            get;
            set;
        }
    
        public virtual string Tip4
        {
            get;
            set;
        }
    
        public virtual string Tip5
        {
            get;
            set;
        }
    
        public virtual string Tip6
        {
            get;
            set;
        }

        #endregion

        #region Navigation Properties
    
        public virtual ICollection<City> Cities
        {
            get
            {
                if (_cities == null)
                {
                    var newCollection = new FixupCollection<City>();
                    newCollection.CollectionChanged += FixupCities;
                    _cities = newCollection;
                }
                return _cities;
            }
            set
            {
                if (!ReferenceEquals(_cities, value))
                {
                    var previousValue = _cities as FixupCollection<City>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupCities;
                    }
                    _cities = value;
                    var newValue = value as FixupCollection<City>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupCities;
                    }
                }
            }
        }
        private ICollection<City> _cities;

        #endregion

        #region Association Fixup
    
        private void FixupCities(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (City item in e.NewItems)
                {
                    item.Country = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (City item in e.OldItems)
                {
                    if (ReferenceEquals(item.Country, this))
                    {
                        item.Country = null;
                    }
                }
            }
        }

        #endregion

    }
}
