//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace MVCSite.DAC.Entities
{
    public partial class OperationLog
    {
        #region Primitive Properties
    
        public virtual int ID
        {
            get;
            set;
        }
    
        public virtual int LogID
        {
            get;
            set;
        }
    
        public virtual int KeyObjType
        {
            get;
            set;
        }
    
        public virtual System.Guid KeyGUID
        {
            get;
            set;
        }
    
        public virtual int RelatedObjType
        {
            get;
            set;
        }
    
        public virtual System.Guid RelatedObjGUID
        {
            get;
            set;
        }
    
        public virtual byte OperationType
        {
            get;
            set;
        }
    
        public virtual string IP
        {
            get;
            set;
        }
    
        public virtual System.DateTime OperationTime
        {
            get;
            set;
        }
    
        public virtual int UserID
        {
            get;
            set;
        }
    
        public virtual byte Flag
        {
            get;
            set;
        }

        #endregion

    }
}
