//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace MVCSite.DAC.Entities
{
    public partial class Pagevar
    {
        #region Primitive Properties
    
        public virtual string pagevar1
        {
            get;
            set;
        }
    
        public virtual int counts
        {
            get;
            set;
        }
    
        public virtual Nullable<int> counts_nonusers
        {
            get;
            set;
        }
    
        public virtual int signups
        {
            get;
            set;
        }
    
        public virtual Nullable<int> female
        {
            get;
            set;
        }
    
        public virtual decimal conversion
        {
            get;
            set;
        }
    
        public virtual Nullable<decimal> femaleconver
        {
            get;
            set;
        }
    
        public virtual Nullable<decimal> intent
        {
            get;
            set;
        }
    
        public virtual Nullable<int> completedprofiles
        {
            get;
            set;
        }
    
        public virtual Nullable<decimal> purchase
        {
            get;
            set;
        }
    
        public virtual Nullable<int> nologins
        {
            get;
            set;
        }
    
        public virtual Nullable<int> nologinssevendaysago
        {
            get;
            set;
        }
    
        public virtual Nullable<int> completedprofilessevendaysago
        {
            get;
            set;
        }

        #endregion

    }
}
