//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace MVCSite.DAC.Entities
{
    public partial class QueuedEmails
    {
        #region Primitive Properties
    
        public virtual System.Guid ID
        {
            get;
            set;
        }
    
        public virtual string Sender
        {
            get;
            set;
        }
    
        public virtual string Receiver
        {
            get;
            set;
        }
    
        public virtual string Title
        {
            get;
            set;
        }
    
        public virtual string Body
        {
            get;
            set;
        }
    
        public virtual System.DateTime EnterTime
        {
            get;
            set;
        }
    
        public virtual byte SiteType
        {
            get;
            set;
        }
    
        public virtual int EmailType
        {
            get;
            set;
        }

        #endregion

    }
}
