//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace MVCSite.DAC.Entities
{
    public partial class TourVendorPromo
    {
        #region Primitive Properties
    
        public virtual int ID
        {
            get;
            set;
        }
    
        public virtual string PromoName
        {
            get;
            set;
        }
    
        public virtual int PromoValue
        {
            get;
            set;
        }
    
        public virtual double PromoPercent
        {
            get;
            set;
        }
    
        public virtual byte SortNo
        {
            get;
            set;
        }
    
        public virtual Nullable<bool> OpenToUse
        {
            get;
            set;
        }
    
        public virtual Nullable<int> MinTouristsToUse
        {
            get;
            set;
        }
    
        public virtual Nullable<int> MinValueToUse
        {
            get;
            set;
        }
    
        public virtual System.DateTime BeginDate
        {
            get;
            set;
        }
    
        public virtual System.DateTime EndDate
        {
            get;
            set;
        }
    
        public virtual string DateRange
        {
            get;
            set;
        }
    
        public virtual System.DateTime EnterTime
        {
            get;
            set;
        }
    
        public virtual System.DateTime ModifyTime
        {
            get;
            set;
        }
    
        public virtual Nullable<int> GuideID
        {
            get;
            set;
        }
    
        public virtual Nullable<int> TourID
        {
            get { return _tourID; }
            set
            {
                try
                {
                    _settingFK = true;
                    if (_tourID != value)
                    {
                        if (Tour != null && Tour.ID != value)
                        {
                            Tour = null;
                        }
                        _tourID = value;
                    }
                }
                finally
                {
                    _settingFK = false;
                }
            }
        }
        private Nullable<int> _tourID;

        #endregion

        #region Navigation Properties
    
        public virtual Tour Tour
        {
            get { return _tour; }
            set
            {
                if (!ReferenceEquals(_tour, value))
                {
                    var previousValue = _tour;
                    _tour = value;
                    FixupTour(previousValue);
                }
            }
        }
        private Tour _tour;

        #endregion

        #region Association Fixup
    
        private bool _settingFK = false;
    
        private void FixupTour(Tour previousValue)
        {
            if (previousValue != null && previousValue.TourVendorPromoes.Contains(this))
            {
                previousValue.TourVendorPromoes.Remove(this);
            }
    
            if (Tour != null)
            {
                if (!Tour.TourVendorPromoes.Contains(this))
                {
                    Tour.TourVendorPromoes.Add(this);
                }
                if (TourID != Tour.ID)
                {
                    TourID = Tour.ID;
                }
            }
            else if (!_settingFK)
            {
                TourID = null;
            }
        }

        #endregion

    }
}
