//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace MVCSite.DAC.Entities
{
    public partial class UserPromo
    {
        #region Primitive Properties
    
        public virtual int ID
        {
            get;
            set;
        }
    
        public virtual Nullable<int> UserID
        {
            get;
            set;
        }
    
        public virtual Nullable<int> BookingID
        {
            get;
            set;
        }
    
        public virtual Nullable<int> PromoID
        {
            get;
            set;
        }
    
        public virtual bool isPromoUsed
        {
            get;
            set;
        }

        #endregion

    }
}
