//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace MVCSite.DAC.Entities
{
    public partial class UserWish
    {
        #region Primitive Properties
    
        public virtual int ID
        {
            get;
            set;
        }
    
        public virtual int UserID
        {
            get;
            set;
        }
    
        public virtual int TourID
        {
            get { return _tourID; }
            set
            {
                if (_tourID != value)
                {
                    if (Tour != null && Tour.ID != value)
                    {
                        Tour = null;
                    }
                    _tourID = value;
                }
            }
        }
        private int _tourID;
    
        public virtual System.DateTime EnterTime
        {
            get;
            set;
        }
    
        public virtual System.DateTime ModifyTime
        {
            get;
            set;
        }
    
        public virtual string TourName
        {
            get;
            set;
        }
    
        public virtual double SugRetailPrice
        {
            get;
            set;
        }
    
        public virtual double NowPrice
        {
            get;
            set;
        }
    
        public virtual string TourImgPath
        {
            get;
            set;
        }
    
        public virtual byte BookingType
        {
            get;
            set;
        }

        #endregion

        #region Navigation Properties
    
        public virtual Tour Tour
        {
            get { return _tour; }
            set
            {
                if (!ReferenceEquals(_tour, value))
                {
                    var previousValue = _tour;
                    _tour = value;
                    FixupTour(previousValue);
                }
            }
        }
        private Tour _tour;

        #endregion

        #region Association Fixup
    
        private void FixupTour(Tour previousValue)
        {
            if (previousValue != null && previousValue.UserWishes.Contains(this))
            {
                previousValue.UserWishes.Remove(this);
            }
    
            if (Tour != null)
            {
                if (!Tour.UserWishes.Contains(this))
                {
                    Tour.UserWishes.Add(this);
                }
                if (TourID != Tour.ID)
                {
                    TourID = Tour.ID;
                }
            }
        }

        #endregion

    }
}
